### ISSUE TITLE
Got error msg

### ISSUE THREAD

**Issue by bowodesign** [dzafel/pinterest-pinner#1]
Hi i got error msg like this "Error: Unknown error while creating a pin. " any way to fix it?
thank you

**Comment by zuongthao** [comment]
Hi Dzafel, 

The pin success submited, but i still got this msg "Error: Unknown error while creating a pin. " even the pin is success if I have one board.

I created more boards, the script did not work, there is not any pin submited.
please help, thanks.

**Comment by zuongthao** [comment]
Hi 

I dump _postPin() function and the $http_code return 429.

**Comment by dzafel** [comment]
Hi @zuongthao 
The code works, I just tested and I successfully posted a new pin. This might be a pinterest.com issue when you tried it.
