### ISSUE TITLE
can't get it installed with composer

### ISSUE THREAD

**Issue by gordielachance** [dzafel/pinterest-pinner#10]
Hi, 
I get 

> Could not find package dzafel/pinterest-pinner at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability    

When I try to install it with composer.

How can I avoid this ?

**Comment by pawelatomic** [comment]
Thanks for reporting. I added `minimum-stability` property to `composer.json` and I also added some installation instructions to readme file.
