### ISSUE TITLE
getBoards issue

### ISSUE THREAD

**Issue by RevZer0** [dzafel/pinterest-pinner#16]
Hi!
So, i faced a problem with boards list. Current method return boards for only last 50 pins and if this pins was pinned in one single board - it will will return this one board. I do some research over pinterest site and rewrite this method. So if you want to load just boards list you can use this request.

$this->_loadContent('/resource/ProfileBoardsResource/get/?' . http_build_query([
            'source_url' => sprintf('/%s/', $this->_login),
            'data' => json_encode([
                'options' => [
                    'field_set_key' => 'grid_item',
                    'username' => $this->_login
                ],
            ]),
        ]), null, '/');  
And its necessary to set X-Requested-With: XMLHttpRequest header to this request.

**Comment by RevZer0** [comment]
Also pinterest return "bookmarks" array under response->options collection. Basically it one item array contains base64 encoded string or '-end-' string. So if you will add this bookmarks array into your request options you will receive another chunk of boards if user have more than 50 boards.

the final method will looks like 
```php
    public function getBoards($pagerBookmark = null)
    {
        $options = [
            'field_set_key' => 'grid_item',
            'username' => $this->_login,
        ];
        if (!is_null($pagerBookmark)) {
            $options['bookmarks'] = [$pagerBookmark];
        }
        $this->_loadContent('/resource/ProfileBoardsResource/get/?' . http_build_query([
            'source_url' => sprintf('/%s/', $this->_login),
            'data' => json_encode([
                'options' => $options,
            ]),
        ]), null, '/', true);
        $boards = [];
        if (isset($this->_response_content['resource_response']['data'])) {
            foreach ($this->_response_content['resource_response']['data'] as $board) {
                $boards[$board['id']] = $board['name'];
            }
        }
        if (isset($this->_response_content['resource']['options']['bookmarks'])) {
            $bm = $this->_response_content['resource']['options']['bookmarks'][0];
            if ($bm !== '-end-') {
                $nextPageBoard = $this->getBoards($bm);
                $boards = array_replace($boards, $nextPageBoard);
            }
        }
        return $boards;
    }
```

**Comment by dzafel** [comment]
I actually used different way of getting all boards, your code didn't work for me. But thanks anyway for reporting the issue and help.
