### ISSUE TITLE
Error getting App Version

### ISSUE THREAD

**Issue by bowodesign** [dzafel/pinterest-pinner#17]
Hi sorry newbie here, just wonder why i got this error
`Error getting App Version from P.main.start() JSON data.`

this is code i try to use
```
require('vendor/autoload.php'); 

use dzafel\PinterestPinner\Pinner;

try {
    $pinterest = new PinterestPinner\Pinner;
    $pin_id = $pinterest->setLogin('Your Pinterest Login')
        ->setPassword('Your Pinterest Password')
        ->setBoardID('Pinterest Board ID')
        ->setImage('Image URL')
        ->setDescription('Pin Description')
        ->setLink('Pin Link')
        ->pin();
} catch (PinterestPinner\PinnerException $e) {
    echo $e->getMessage();
}
```

just like sample you give on the front, any idea why i got error sir?

**Comment by dzafel** [comment]
Hi @bowodesign looks like Pinterest changed their code again. The `P.main.start()` function does not exist anymore, they use `<script type="application/json">` tag instead. I had to update the function that gets config JSON from pinterest. Thanks for reporting the issue. Please update PinterestPinner to 2.0.4
