### ISSUE TITLE
getting timeout issue

### ISSUE THREAD

**Issue by sanmed02** [dzafel/pinterest-pinner#18]
After multiple request to the server, I got this error.
[status code] 429 [reason phrase] Unknown' 
they block access after x requests ... Any advices to fix that please ?

**Comment by dzafel** [comment]
> HTTP Status Code 429: The user has sent too many requests in a given amount of time ("rate limiting")
@sanmed02 So yes, they block you, you make too many requests. Nothing I can do about it. You need to add some limitations to your script.
