### ISSUE TITLE
Exception issue

### ISSUE THREAD

**Issue by evivz** [dzafel/pinterest-pinner#19]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://www.pinterest.com/resource/PinResource/create/ [status code] 400 [reason phrase] Bad Request' in /Applications/XAMPP/xamppfiles/htdocs/runproject/pin/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/runproject/pin/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /Applications/XAMPP/xamppfiles/htdocs/runproject/pin/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(109): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /Applications/XAMPP/xamppfiles/htdocs/runproject/pin/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /Applications/XAMPP/xamppfiles/htdocs/runproject/pin/vendor/ in /Applications/XAMPP/xamppfiles/htdocs/runproject/pin/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89

I am getting above error any way to fix it?

**Comment by dzafel** [comment]
Sorry, I can't recreate your issue. Please post your code so I can test or help you find the issue.

**Comment by evivz** [comment]
Composer updated to latest code and it worked.

Thanks.
