### ISSUE TITLE
Error getting CSRFToken

### ISSUE THREAD

**Issue by gordielachance** [dzafel/pinterest-pinner#2]
Is this code out of date ? I get "Error getting CSRFToken"...
Thanks !

**Comment by dzafel** [comment]
Hi @gordielachance 
I don't see any issue, I can successfully create a pin, please check your login credentials and try again.

**Comment by gordielachance** [comment]
Got it working.
But sometimes it does not work.  Maybe because it fails if the script is called to much.

**Comment by dzafel** [comment]
@gordielachance check the http code you get back, maybe you have been banned, there is a pinterest.com server issue or you simply make too many requests.

**Comment by gordielachance** [comment]
Yes, I made too many requests.
This code allows to be warned about it : https://github.com/dzafel/pinterest-pinner/pull/5
