### ISSUE TITLE
Any plans to support Creating Board?

### ISSUE THREAD

**Issue by evivz** [dzafel/pinterest-pinner#20]
Sorry this is not an issue but I don't know how to request any feature.

Any plans to support creation of boards via this repo?

Or any other way you know to create list of boards?

**Comment by dzafel** [comment]
Currently I don't have any plans for that, sorry. However you can use the official Pinterest API:
https://developers.pinterest.com/docs/api/overview/
It is now possible to create boards and pins using this API.
