### ISSUE TITLE
Hi ! Do you have an idea about this ?

### ISSUE THREAD

**Issue by gordielachance** [dzafel/pinterest-pinner#22]
Hi dzafel !
Sorry to write you here as this is not completely related to your pinterest-pinner code.
I don't know if you remember me, I made some commits in this repo a while ago, while I was coding a Wordpress plugin to backup Pinterest.
The functions that communicates with Pinterest have been inspired by your code.

Well, I have an issue since a while :
I can't retrieve the secret boards anymore.  Not sure why; but this is annoying for me :/
I already did try to find out what's going on but I failed.
I was wondering if you had an idea about this.
Maybe this is related to something like getting boards from /USERNAME instead of /ME or something like this.
Maybe you understand their "api" more than me, so, if you have any idea, I would be very grateful :)

Here's my repo : https://github.com/gordielachance/pinterest-importer/blob/master/pinim-class-bridge.php
And the functions related to pinterest : https://github.com/gordielachance/pinterest-importer/blob/master/pinim-class-bridge.php
issue report with some informations : https://github.com/gordielachance/pinterest-importer/issues/12

Thanks !

**Comment by pawelatomic** [comment]
@gordielachance I’m sorry, your code is different than mine, and I don’t have any private time to fix your code. I don’t see any issues with getting secret boards using my code, so please either install my library or see how I fetch boards here: https://github.com/dzafel/pinterest-pinner/blob/master/PinterestPinner/Pinner.php#L270

**Comment by dzafel** [comment]
@gordielachance I’m sorry, your code is different than mine, and I don’t have any private time to fix your code. I don’t see any issues with getting secret boards using my code, so please either install my library or see how I fetch boards here: https://github.com/dzafel/pinterest-pinner/blob/master/PinterestPinner/Pinner.php#L270

**Comment by gordielachance** [comment]
Hi @dzafel, sorry to bother you about this again.  Still trying to make it work with Wordpress.

I started back from your code, and only changed the way requests are done, using [Wordpress HTTP API](https://codex.wordpress.org/HTTP_API) instead of GuzzleHttp.
I'm doing this because it seems a bad idea to load another library when Wordpress does pretty much the same thing.

The error I got is **HTTP error (/me/): 404 Not Found** : it seems that the user is not logged when accessing this url.  I suspect that there is a problem with the response from _/resource/UserSessionResource/create/_.  Maybe this is related to cookies.
Would you mind having a look ?  I guess this should be a minor thing, I would be so glad to make this work !
Here's my commit : https://github.com/gordielachance/pinterest-pinner/commit/ccb27b5fd548b73b5005829eb58d31c86a5e02f1

Thanks a lot.
