### ISSUE TITLE
Oauth authentification ?

### ISSUE THREAD

**Issue by gordielachance** [dzafel/pinterest-pinner#4]
Hi, I don't know if it it possible, but I would like to know if it would be technically possible to adapt your code and authentificate to Pinterest with Oauth.
I'm working with your script and the problem is that, in the actual version, I would need to store user's passwords (and make curl request with "clear" logins and passwords), which I think is not very secure.

Any opinions on this ?

**Comment by dzafel** [comment]
@gordielachance This is not possible, pinterest.com does not have any official API to add pins, my library is just a workaround. It's not secure to store plain passwords and I don't recommend using the library on any website/webapp as it can stop working anytime and I may have no fix
