### ISSUE TITLE
Having a session enabled ?

### ISSUE THREAD

**Issue by gordielachance** [dzafel/pinterest-pinner#9]
...(https://github.com/dzafel/pinterest-pinner/issues/4)...
And is it possible to have a session enabled so it's not necessary to re-log once done ?
Eg. getUserData() should not relog if there is a session enabled ?
This would allow not to be banned for too much resquests for the CSRFToken...

?

**Comment by dzafel** [comment]
@gordielachance One instance of this library will log in only once, ie you can do more actions and it will login only once:
```
$pinterest = new PinterestPinner\Pinner;
$pinterest->setLogin('login');
$pinterest->setPassword('password');

$user_data = $pinterest->getUserData();

$boards = $pinterest->getBoards();

$pinterest->setBoardID('board id')
    ->setImage('Image URL')
    ->setDescription('Pin Description')
    ->setLink('Pin Link');
$pin = $pinterest->pin();
```

**Comment by gordielachance** [comment]
But only on the same page (script) ?
It will not be logged anymore after that but will have to relog ?
Eg. If I go to another page to do another action related to PinterestPinner
?
Thanks and sorry for all of my questions...

2015-04-09 10:35 GMT+02:00 Paweł Ciesielski <notifications@github.com>:

**Comment by pawelatomic** [comment]
It's up to you how will you use this library, you can log in once and then keep the $pinterest as a static property in a static class to access it from other places in your app. But it's not possible now to save the session and load it on different page (eg. after page refresh), you need to log in again.
